# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

# https://github.com/BetaHuhn/repo-file-sync-action

# Synchronization for the.github repository
kubecub/.github:
  - source: LICENSE
    dest: LICENSE 
  - source: scripts/LICENSE/
    dest: scripts/LICENSE/
    replace: true
  - source: .github/
    dest: .github/
    replace: true
    exclude: |
      workflows/
      sync.yml

kubecub/community:
  - source: LICENSE
    dest: LICENSE 
  - source: scripts/LICENSE/
    dest: scripts/LICENSE/
    replace: true
  - source: .github/workflows/
    dest: .github/workflows/
    exclude:
      - e2e-test.yml
      - sync.yml
  - source: .github/
    dest: .github/
    replace: true
    exclude: |
      sync.yml

group:
  # first group：common to all warehouses
  # TODO: add the required warehouse here
  - repos: |
      kubecub/github-label-syncer
      kubecub/RemoteOps-scripts
      kubecub/kube-im
      kubecub/CloudBuildAI
      kubecub/log
      kubecub/automation
      kubecub/kubecub
      kubecub/feishu-sheet-parser
      kubecub/docs
    files: 
      # - source: .gitingore
      #   dest: .gitingore
      #   replace: false
      - source: LICENSE
        dest: LICENSE
        replace: false
      - source: .github/workflows/
        dest: .github/workflows/
        exclude: |
          e2e-test.yml
          sync.yml
      - source: scripts/githooks/
        dest: scripts/githooks/
        replace: true
      - source: scripts/LICENSE/
        dest: scripts/LICENSE/
        replace: false

  # # second group：omplex layered architecture, common to go language projects
  # TODO: add the required warehouse here
  # - repos: |
  #     kubecub/github-label-syncer
  #     kubecub/kube-im
  #     kubecub/automation
  #     kubecub/kubecub
  #   files: 
  #     # - source: .gitingore
  #     #   dest: .gitingore
  #     #   replace: false
  #     - source: LICENSE
  #       dest: LICENSE
  #       replace: false
  #     - source: .github/workflows/
  #       dest: .github/workflows/
  #       exclude: |
  #         e2e-test.yml
  #         sync.yml
  #     - source: scripts/githooks/
  #       dest: scripts/githooks/
  #       replace: true